import css from "./global.css"
import Navbar from "@/components/Navbar"
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Primer proyecto',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}

      <body >
        <Navbar />
        <main className="container mt-10 mx-auto h-[calc(100vh-7rem)] flex justify-center  ">
          {children}
        </main>

      </body>
    </html>
  );
}
