/* tiene como funcion englobar a toda 
la pagina para asi tener una SPA ( single page application)*/


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
